### ISSUE TITLE
What would implementing WebVMT mean for user agents?

### ISSUE THREAD

**Issue by tidoust** [w3c/sdw#1019]
First examples in the [Proposed Solution](https://w3c.github.io/sdw/proposals/geotagging/webvmt/#proposedsolution) section show an HTML page composed of a `<video>` element and a `<div>` element that is to contain the map.

The link between the `<div>` element and the WebVMT track seems to be made within the WebVMT file itself through the `div-id` map property. I believe that this is wrong: the WebVMT file is embedded in the HTML page, and should not know anything about the page. The same WebVMT file could be used in different HTML pages for instance. The association with the `<div>` element should rather be made in the HTML page itself.

More broadly, this begs the question of what it would mean for a user agent to implement WebVMT. Does it:

1. Parse WebVMT files and trigger map cues at the right time, as `VMTCue` instances (interface which has yet to be defined)?
2. And render the map all by itself alongside the video?

User agents need to natively support map rendering to be able to do 2. They do not for the time being, and the Web platform does not have any notion of map for the time being. Something like the MapML proposal could perhaps change that situation in the future.

It would be useful to clarify the goal. If it includes 2., I believe this introduces a dependency on defining a notion of map on the Web, as linking to a generic `<div>` element and expecting rendering magic to happen is likely going to trigger interoperability issues, especially if you envision that the user can interact with the rendered map (pan, zoom, rotate, click, etc.). That is not necessarily a huge problem per se, but seems worth keeping in mind.

Alternatively, 2. could be something we envision as a longer term goal, but in that case we'll probably need to think about the transition between implementations that only support 1. and implementations that support both 1. and 2, e.g. how an application can detect that a user agent supports map rendering.

**Comment by rjksmith** [comment]
Good points.

I'd originally thought of _requiring_ the `div-id` map property to link the `<video>` to a `<div>` element, but then relaxed this to an _optional parameter_ so that if the `div-id` (or the `tile-url`) was omitted then a default value would be used. However, I agree with your analysis: the VMT file should be agnostic of the web page.

What if `div-id` and `tile-url` were attributes of the `<track>` element instead, alongside the `src` attribute? That would provide the same connection within the HTML page and make the VMT file independent of it, which may be a better solution. I've also been thinking about a `map-api` property to specify the map renderer (API), e.g. Google Maps, OpenLayers, Leaflet, etc. If all three properties were attributes of the `<track>` element, that would provide sufficient information for the user agent to load the correct map rendering scripts.

This system works in a similar way to embedded YouTube video content, which can be included in a self-populating `<iframe>` element. Rendering the map in an `<iframe>`, rather than a `<div>` element, would add some complexity to synchronisation messaging, as two discrete web pages would have to communicate, but it might be worth considering. Current web map APIs use a `<div>` element as their root.

I think the goal is to parse the VMT file and issue map `VMTCue`s to a receiver at the correct time, though I've not yet specified that interface, i.e. item 1 only. I believe that information flows from the video player to the map controller _only_, and never in the opposite direction. The `VMTCue` interface should provide a natural boundary between items 1 and 2, so the rendering process is entirely separate though may have a type influenced by the `map-api` property.

As map rendering is not supported in user agents currently, there is a more general question of how to handle the transition if they do support it in future, which is probably beyond the scope of this project, though still worth discussing in a separate thread.

**Comment by cmheazel** [comment]
We did this back around 2008-9.  We extracted the KLV stream from an MPEG-2 video, converted it into KML, and displayed both the frame footprint as well as movers on the video display.  A slidebar allowed you to advance or retard the frame.  Most of this was done using off the shelf codecs and playback tools.  I'll dig through my archives for details.

**Comment by rjksmith** [comment]
Chuck,
Thanks for your comments. I'd be interested to know the details of your previous work. Please post a link if it was published, or contact me directly. Many thanks.

**Comment by cmheazel** [comment]
It has been a while.  The work was done as part of a proof of concept for MISB Std 0903 and an early version of STANAG 4676.  I have managed to find a Power Point:
[18_09_VMTI-MISB 20100513.zip](https://github.com/w3c/sdw/files/1943091/18_09_VMTI-MISB.20100513.zip)
The latest version of the KML Users Guide is at [MISB](http://www.gwg.nga.mil/misb/trm_pubs.html)
I have also found a copy of the source code, although not one with the KML output.  I will have to get permission to provide that.

**Comment by cmheazel** [comment]
ESRI has their view of how users will integrate FMV and geospatial.  See #1020 for links to their FMV Add-in.

**Comment by rjksmith** [comment]
Many thanks for your feedback

**Comment by rjksmith** [comment]
I've now revised the [explanatory spec for WebVMT](http://w3c.github.io/sdw/proposals/geotagging/webvmt/) to move the `div-id` and `tile-url` parameters to &lt;track&gt; element attributes, and successfully implemented these changes in the tech demo to verify the new design.

This highlights another inferred step in the user agent development process, which precedes steps 1 and 2, listed above by @tidoust:

0. User agent support for WebVMT can be implemented in Javascript, using the &lt;track&gt; element as described in the spec, without requiring any change to the agent itself. The modified track element doesn't cause a problem as HTML handles errors gracefully and the unknown attributes should be simply ignored by the parser, allowing the WebVMT format to be used with immediate effect.

Steps 1 and 2 can occur in either order, as each must define an interface (cue or map respectively) which can be incorporated into the existing solution from step 0. Hence, step 2 is linked to WebVMT development, though not in a way that obstructs its progress, and should be considered as a separate issue.

Thanks to @cmheazel for moving his comments to a separate discussion in [issue #1020](https://github.com/w3c/sdw/issues/1020)

If there are no further queries on this issue, I will close it.

**Comment by tidoust** [comment]
Thanks @rjksmith, I would simply suggest marking up (as an issue or an editor's note) the fact that the meaning of `div-id` and `tile-url` for user-agents is an open question at this stage but that the vision is that user-agents would take care of the rendering longer term.

**Comment by rjksmith** [comment]
Editor's note added
