### ISSUE TITLE
Group review of roadmap

### ISSUE THREAD

**Issue by lvdbrink** [w3c/sdw#1065]
Once the first version of the SDW roadmap is published at https://github.com/w3c/web-roadmaps, the SDWIG group should review it. 
- Is everything well described and are the references correct?
- Is everything in its right category?
- Are there gaps i.e. things missing from the roadmap? Or things that shouldn't be on there?

**Comment by tidoust** [comment]
The first version of the SDW roadmap can now be reviewed at:
https://w3c.github.io/web-roadmaps/sdw/

Another question that comes to mind: What info could the generated tables at the end of each section contain? The "Current implementations" column is mostly useless for now because it was meant for specs implemented in browsers, and SDW specs do not necessarily target browsers. Is there additional info somewhere that would be worth adding? (even better if that info can be retrieved automatically).

Hand-drawn icons will be replaced with colorful ones once the grouping is considered stable. It would be good if we could stick to similar icons as used in other roadmaps (and we can probably reuse some of the existing icons, notably for the "capture" one). If someone has design skills and is willing to give it a shot, that would be fantastic!

**Comment by ogcscotts** [comment]
This really looks superb and is will also be a great tool for those exploring how spatial data can be enabled or used on the web. Good work to all!

Under "Transform spatial data," we should include the OGC Community standard i3S (Indexed 3D Scene Layers) as it is an official standard and implemented. But then again, maybe i3S and  3D Tiles are more appropriately placed in the "publish spatial data" category.

**Comment by MichaelGordon** [comment]
A couple of comments from @PeterParslow -

"1. in the 'represent spatial data' section of the road map https://w3c.github.io/web-roadmaps/sdw/represent.html, I think you'll find it helpful to distinguish more between semantic & syntactic standards. Understandably, you mainly have syntactic ones there but SSN, Time Ontology, CityJSON, VCard Ontology & the ISA Core Vocabulary are more semantic. I think there are a lot of other semantic standards that are in wide use, at least in their particular domains, and it's at the level of semantics that most of the interoperability difficulties occur. Think INSPIRE, IHO, WMO, OneGeology.

2. I can't quite see why Cesium 3D Tiles is listed as a "transform" standard." 

(as per @ogcscotts comment above I'd also agree that i3s and 3D Tiles would be more appropriate in "publish spatial data")

**Comment by lvdbrink** [comment]
The "Transform" category is, even if I wouldn't move Cesium and i3S to "Publish", quite small - only 7 items. Mostly these are in this category because they have functionality for partitioning data, which I've regarded as a kind of transformation. 

We could move Cesium and i3S to Publish, but maybe the question is if we need the Transform category at all. Any ideas?

**Comment by lvdbrink** [comment]
We will discuss the roadmap at the next f2f meeting. I would like input and discussion on the following: 
- The current grouping into categories. The "transform" category may not work - or would it help to simply rename it to "Partition"? Can we come up with different categories?
- Is there a standard that can be added that does partitioning for raster data? 
- Do we want other functionality in the roadmap tables instead of the column listing browser implementations? 

Any other input / discussion is also welcome. 

This could become a good resource, providing a compact overview of the spatial web standards landscape. Let's put some thought into it!
