### ISSUE TITLE
W3C LBD reach out - 2D and 3D CAD geometry for building projects

### ISSUE THREAD

**Issue by mathib** [w3c/sdw#1143]
Dear members of the Spatial Data Group,

This is a message of the [Linked Building Data Community Group](https://w3c-lbd-cg.github.io/lbd/). We are defining web ontologies (OWL) and methods to model buildings, including building topology, building products and properties. To make this approach more attractive for industry, we need to pay attention to geometry. However, geometry in a Linked Data context is currently considered out of scope as it is not only used in the construction industry, but also by mechanical engineers (product modelling), scientist, artists, spatial planners, chemists, etc. For this reason, we try to reach out to this group (and potential other related groups), to achieve a more uniform approach towards geometry in a Linked Data context.

Currently, based on a quick scan through the output documents of the SDW group, we mostly see (geo)spatial data used in applications for sensors, efforts regarding a time ontology, CityJSON, etc. Construction industry partners currently use a lot of CAD applications to create drawings and 3D models in different formats (DWG, OBJ, Collada, glTF, etc.). They hardly use WKT and GML and more and more of the data is 3D, so GeoSPARQL on its own cannot be used directly for common building projects trying to adapt Linked Data technologies. Another concern is that the proposed methods to use geometry in a Linked Data context should be straightforward enough (and modular), to increase the adoption by industry.

Is it currently within the scope/interests of this group to work around this kind of geometry? If so, it might be beneficial to connect between our two W3C groups to exchange ideas and use cases. I see some potential overlap with https://github.com/w3c/sdw/issues/1095 and https://github.com/opengeospatial/geosemantics-dwg/issues/9, but maybe SDW/OGC members can give better feedback here?

Best regards,

Mathias Bonduel for the W3C Linked Building Data Community Group

**Comment by chris-little** [comment]
@mathib Perhaps the approach that seems to be happening in environmental science, in particular weather and climate, may be a useful model. There was a peripheral discussion in the SDW WG  involving @rob-metalinkage. In essence, the existing **data** silos  stay in their local, compact, binary, efficient formats, surrounded by their domain-specific tool ecosystems and domain experts, because no-one is going to retro-convert that enormous amount of data, at great expense and disruption into more voluminous data serializations. But, the metadata describing that data, including how it can be queried and reasoned about, should migrate into the semantic linked web world.
So I suggest an approach that does not expend effort on yet more geometry format conversion tools, or one format to rule them all, but work in the metadata/catalogue/vocabulary/ontology area to automate invocation of the existing tools correctly.
HTH, Chris

**Comment by mathib** [comment]
@chris-little Interesting! In general, I think along the same lines in my personal research. Some members of our group were/are also actively investigating a more RDF-based description of geometry, e.g. in a context of parametric geometry where the parametrics have to be accessible as Linked Data.

This brings me to the following questions:
* is this a general view endorsed by the SDW group or rather a personal opinion?
* did you or other members of the SDW/OGC group developed approaches/ontologies/... to implement this view? Or is there in the SDW/OGC group a will to develop something here?

**Comment by chris-little** [comment]
@mathib Firstly, it is my personal opinion, but there is some consensus around it and @rob-metalinkage did develop a QB4ST (geo-spatial datacube) ontology restricting the generic RDF QB data cube. It is a [W3C Technical Note](https://www.w3.org/TR/qb4st/).
@Fransie proposed a project to develop a spatial ontology, similar to the OWL-Time ontology. See [SDW Issue #1095](https://github.com/w3c/sdw/issues/1095).

**Comment by FransKnibbe** [comment]
Hi Mathias,

Although I am not in the Spatial Data on the Web Interest Group (SDWIG), I
would like to share my view. Chris mentioned a 'one format to rule them
all' approach. What I propose is a variation on that theme. In condensed
form it could be called 'one model to underpin them all', with 'model'
meaning a universal model for spatial data, and 'them' meaning storage
formats, exchange formats, functions, software libraries, software, etc.

This idea was partly inspired by trying to use the same spatial data in a
GIS, BIM and Computer Graphics (CG) contexts. As you may have also
experienced, that is not easy because those domains use different ways of
working with spatial data. But although the domains work differently on the
surface, if you drill down to underlying principles the foundations are the
same. At the core, working with geometry is purely mathematical, so if all
the different domains could be based on a single model with a mathematical
core, it should be possible to achieve much better interoperability across
the many ways in which software can manipulate spatial data. In this line
of reasoning, such a model does not really have to be a web ontology, but I
think building it as a web ontology makes a lot of sense, because the
semantic web by nature is a cross-domain effort and space by nature is a
cross-domain phenomenon. Also, making it a web ontology should lower the
threshold for people and organisations with different backgrounds to
collaborate, thus increasing the likelihood of coming up with a truly
robust and universal model. And yes, I think also this will increase the
likelihood of the model being as simple as possible. Furthermore, I imagine
such a model to be helpful for use just within a single domain. At least
within the GIS domain, working with spatial data is much harder than it
needs to be.

I don't think there is an official SDWIG standpoint on this matter, but I
am glad it at least seems to be under consideration here and in the OGC
Geosemantics DWG. Anyway, it seems to me that intensifying the sharing of
ideas between the SDWIG and the LBDCG should be helpful anyway.

Regards,
Frans

Op wo 30 okt. 2019 om 12:44 schreef mathib <notifications@github.com>:

**Comment by lvdbrink** [comment]
Mathias; it would be very useful to at least discuss the possible synergy between our groups. The SDWIG has a [face to face meeting](https://www.w3.org/2017/sdwig/meetings/f2f-5.html) coming up in Toulouse, France next month. We could fit in a discussion on this topic, if it is possible for you and/or others from the LBDCG to join either physically or remotely. Would that be an option? 

Linda
Co-chair of SDWIG

**Comment by mathib** [comment]
Hi Linda, I pass this information to the other members of our group. Personally, I would like to join the meeting remotely. I'll let you know if other members of the LBD group will join

**Comment by lvdbrink** [comment]
Good! I've added an agenda item for this. Keep an eye on the meeting page for remote participation details!

**Comment by lewismc** [comment]
> @chris-little  ...but there is some consensus around it and ...

Yes I agree with that.

@mathib over in the [ESIP Semantic Technologies community](http://wiki.esipfed.org/index.php/Semantic_Technologies) we have been developing and are the stewards of the [Semantic Web for Earth and Environment Terminology](https://github.com/ESIPFed/sweet/) (SWEET) ontology suite which does contain relevant resources worth mentioning here, specifically (but not limited to)
* [Representation Space Geometry](https://github.com/ESIPFed/sweet/blob/4a5378cb048b6f493cfe57fdb85cf4c90f30baa4/src/reprSpaceGeometry.ttl)
* [Representation Space Geometry 3D](https://github.com/ESIPFed/sweet/blob/4a5378cb048b6f493cfe57fdb85cf4c90f30baa4/src/reprSpaceGeometry3D.ttl)

N.B. both of the above resources (like all SWEET resources) are served as linked data via the http://sweetontology.net/ URI e.g. http://sweetontology.net/reprSpaceGeometry. Content negotiation is also available via usual means.

The reason I mention there is is NOT to say that everyone should use them, but it is to say that these representation constructs in SWEET _could_ be used as the framework from which the LBD effort builds out relevant implementations specific to your use cases e.g. 

> ...RDF-based description of geometry, e.g. in a context of parametric geometry where the parametrics have to be accessible as Linked Data

I was discussing some related issues with @pipauwel and am somewhat aware of the work going on over at LBD group. This is a really interesting effort.

**Comment by chris-little** [comment]
@lvdbrink Should we leave this issue open to capture the outcome of the face-to-face meeting in Toulouse, or is having it on the Agenda enough? I am happy to close for the the lattter.

**Comment by lvdbrink** [comment]
Let's keep it open to capture the outcome of the meeting!

**Comment by chris-little** [comment]
I did not have time to to attend any F2F meeting with the LBD people. Was there one? has enough been done? Can we close this issue?

**Comment by lvdbrink** [comment]
SDWIG had a discussion with the Linked Building data group in November. See https://www.w3.org/2019/11/19-sdw-minutes.html#item06
