### ISSUE TITLE
BP8: add explanation of why different coordinate ref systems exist

### ISSUE THREAD

**Issue by lvdbrink** [w3c/sdw#128]
Why different coordinate ref systems exist needs to be explained in a brief overview on the subject for our non-geo-expert readers. 

There is some Dutch text available at Geonovum we can use for this, but it still needs to be translated.

**Comment by 6a6d74** [comment]
In point (14) of his [email to the WG](https://lists.w3.org/Archives/Public/public-sdw-wg/2016Jan/0015.html) @Fransie says:

<em>Best practice 8: Is this based on the [CRS wiki page](https://www.w3.org/2015/spatial/wiki/Coordinate_Reference_Systems)? It seems that WGS84 is recommended. But that is debatable and could be considered American-centric. European guidelines recommend ETRS89. Also, high-precision is not defined. Also, no mention is made of the need to add temporal data if a CRS with an increasing error with time (like WGS84) is needed. Also no mention is made of how to reconcile local CRSs (as in a building plan) with global CRSs. I think CRSs are one of the areas that do require some extra standardisation efforts outside of this document, but which could be instigated by our working group.</em>

**Comment by 6a6d74** [comment]
In his [email to the WG](https://lists.w3.org/Archives/Public/public-sdw-wg/2016Jan/0070.html) Chris suggests some text:

<em>For example, North America and Europe are receding from each other by a couple of centimeters per year, whereas Australia is moving several centimeters per year north-eastwards. So, for better than one meter accuracy in Europe, the European Terrestrial Reference System 1989 (ETRS89) was devised and it is fixed with respect to the European tectonic plate. Consequently, coordinates in the ETRS89 system will change by a couple of centimetres per year with respect to WGS84.</em>

**Comment by PeterParslow** [comment]
Even that is a land based view. It isn't so much that ETRS89 is 'fixed with respect to the European tectonic plate', more that is frequently revised to take account of the tectonic drift. Same result, if you're looking at 'surface' features, but not if you're positioning orbiting features (or presumably ones very deep underground!) - from those perspectives, it's ETRS89 that keeps changing.

That of course is one of the reasons why different CRSs are used. The other (in my view) being the useful of Cartesian projections e.g. for calculating areas. All depends on the use case - although again, for many 'low resolution' use cases some differences are small. Others (web Mercator vs WGS84 or ETRS89) can be very large (e.g. 40km?) in Arctic areas.

**Comment by lvdbrink** [comment]
Made changes to the BP about CRS incorporating comments above.
