### ISSUE TITLE
[SDW Best Practices Update]: DCAT2 Update

### ISSUE THREAD

**Issue by situx** [w3c/sdw#1297]
DCAT 2 update

**Comment by PeterParslow** [comment]
I see in https://github.com/w3c/sdw/issues/1084 and elsewhere in conversations in the community that there are a variety of views on 'best practice' use of DCAT; some of those are new for DCAT 2 because it introduces new features.

That means I'm not sure I can document a best practice for using DCAT2, so what I have done is propose changes that I believe are not controversial but not propose as best practice using any of the new features of DCAT2 such as dcat:service / dcat:DataService, or embedding catalogs within catalogs.

I have:

- corrected the reference for the (RDF) namespace (because the W3C namespace is versionless, as DCAT2 is backwards compatible with DCAT)
- updated the definition of Dataset (12.1.1 NOTE)
- corrected the reference for dcat:bbox in BP5
- corrected the reference for example 21 in BP6
- changed three references in BP14
- corrected the references in BP15 (I can only see VOCAB-DQV mentioned in DCAT2; & EXAMPLE64.
- changed Examples 65 in BP15 because DCAT2 has spatialResolutionInMeters & GeoDCAT-AP now recommends using that for spatialResolutionAsDistance when the unit is metres (Example 64 already showed this).
- changed the explanation at 13.3 of the relationship between DCAT/DCAT-AP/GeoDCAT-AP/DCAT2; I think I've got it right!
- corrected references in editors note & table column heading in Annex A

Quite a lot of updates had already been done:
There is an editor's note in BP5 which already used DCAT2 (about bbox); similarly, the examples there which draw on GeoDCAT-AP use DCAT2, as does the second example under EXAMPLE 21. Similarly, BP15 had already been updated (with the exceptions noted above). I guess whoever did these assumed we would drop DCAT1 from the list of Informative references & re-use the identifier/link.

Question: should we retain DCAT1 in the list of informative references?

The NOTE in 12.1.1 reminded me that there are other "published" mappings than GeoNovum's, neither of which have been updated for DCAT 2:

- GeoCat, 2015-2017: https://github.com/GeoCat/iso-19139-to-dcat-ap/blob/master/documentation/Mappings.md
- W3C working draft, 2016-2018: https://www.w3.org/2015/spatial/wiki/ISO_19115_-_DCAT_-_Schema.org_mapping

Here's one we made in the UK as part of a Geospatial Commission project ("DD3") which concentrates on the UK (INSPIRE) profile of ISO 19115:2003: https://github.com/agiorguk/gemini/issues/41 (although I'm not sure I agree now with what we said about theme & subject!)

Should we update the NOTE at 12.1.1? Some parts of GeoDCAT-AP have been updated to DCAT 2 even while the revision of DCAT-AP itself has remained in "working draft" since 2020 (https://joinup.ec.europa.eu/collection/semantic-interoperability-community-semic/solution/dcat-application-profile-data-portals-europe/release/201-0). For example, use of dcat:bbox
