### ISSUE TITLE
[SDW Best Practices Update]: Integration of JSON-LD search contexts

### ISSUE THREAD

**Issue by situx** [w3c/sdw#1299]
Spatial data should be discoverable by search engines and there are various microformats which can achieve this.
One example is a JSON-LD context which may be added to contain spatial information.
We should figure out and explain best practices for that and examine the support of search engines for search contexts

**Comment by VladimirAlexiev** [comment]
Can you elaborate a bit, maybe add some links? I'm familiar with JSONLD but don't know what is a "search context ".

Is OpenSearch relevant here?

**Comment by situx** [comment]
The idea was to describe contexts such as these for SEO with regards to the integration of geoinformation.
https://developers.google.com/search/docs/advanced/structured-data/intro-structured-data
There are different options for doing this and it would seem that JSON-LD is the recommend one to describe

**Comment by PeterParslow** [comment]
It's well worth noting that the "Google search context" that situx links to includes Schema.org for its semantics (a defined subset, but also potentially over ridden by Google's own interpretation!) encoded in JSON-LD as an example, but RDFa and HTML micro format also listed. In fact, most of Google's guide focuses on Schema.org encoded as HTML micro format (itemscope, itemprop) - not JSON-LD.

**Comment by VladimirAlexiev** [comment]
Google and the other search engines also process JSONLD. So read the guide for its structure, not for its "itemprop" syntax.

**Comment by situx** [comment]
We need further examples from real-world use cases to determine how geolocation is used in JSON-LD contexts, also concerning:
- Usage of complex geometries
- Geocoordinates
- Which vocabularies are used?

**Comment by PeterParslow** [comment]
See https://www.w3.org/TR/dwbp/#metadata - where this approach is already discussed in the Data on the Web Best Practice. Their Best Practice 2 (provide description metadata) includes a recommendation to add "spatial" (in the Schema.org / DCAT sense). They only provide examples of using that with a link to GeoNames.

We already provide examples (Example 8 of our Best Practice 2).

Noted: this is a specific spatial vocabulary suited to improving search performance (simply because search engines have implemented it).

**Comment by situx** [comment]
We discuss this matter in sufficient detail already, so I am closing this issue
