### ISSUE TITLE
Example 3 in Chapter 9 - inconsistent font colour

### ISSUE THREAD

**Issue by Iza82** [w3c/sdw#1371]
Southwest viewport has a black font colour (should be green).

**Comment by PeterParslow** [comment]
Tricky, because it sits in an HTML pre block; there is no style information within the block. There is no style defined for "pre" in index.html

The block has been copied from https://developers.google.com/maps/documentation/geocoding/requests-geocoding (with the lats & longs truncated from their ridiculous "precision")

Thanks to Firefox, I can tell that it acquires styles from code.hljs.css. I can see that strings which occur after } are treated as plain text rather than "hljs-string" (so "location_type" is black too). I guess this is https://highlightjs.org/, but I don't know which part of our system imports it - so I can't tell what version "we" (or the browsers?) are using, so I don't know whether to raise an issue at https://github.com/highlightjs/highlight.js

I propose "wontfix"
