### ISSUE TITLE
Does the Beacon Link Dump format support use of wild cards?

### ISSUE THREAD

**Issue by 6a6d74** [w3c/sdw#163]
Does the [Beacon link dump format](https://gbv.github.io/beaconspec/beacon.html) allow the use of wild cards / regex in URLs (e.g. URI Template as defined in [RFC6570](https://tools.ietf.org/html/rfc6570))?

**Comment by nichtich** [comment]
BEACON link dump format draft-voss-beacon-001 from July 6, 2014 refers to RFC6570 to specify URI Templates. There is no support of regex in neither BEACON nor RFC6570 but template parameters. The support of templates may be stripped down in a further draft of BEACON because only a little subset has actually been used in the wild, but the most general form is supported. for instance any of:

    #TARGET: http://example.org/{ID}
    #TARGET: http://example.org/?concept={ID}&foo=bar

These templates can be mapped to a `void:uriRegexPattern` to express them in RDF.

P.S: There can be two templates, one for source (RDF subject) and one for target (RDF object).

**Comment by 6a6d74** [comment]
With the current review of SDW best practices, references to the BEACON format have been removed. Apologies ... 

Our rationale is: 
- it’s only draft (version 001, dated Jul-2014 … the Internet Draft expired Jan-2015);
- I don’t see widespread adoption; and 
- the GitHub repositories are not showing current development in the last 3-years

Based on that it's very hard for us to define use of BEACON format as a best practice.

**Comment by nichtich** [comment]
Thanks for notification and giving your reasons! I have not had the time to adjust and publish BEACON specification to current practice and polish a final version. Actually it's widely used in cultural heritage domain but the current state of documentation is poor so I understand your decision.
