### ISSUE TITLE
Need to describe why a Linked Data approach is chosen

### ISSUE THREAD

**Issue by 6a6d74** [w3c/sdw#218]
In Bill's [email to the WG](https://lists.w3.org/Archives/Public/public-sdw-wg/2016Jan/0040.html) he says:

<em>I wonder if we should introduce [the adoption of a Linked Data approach] a little, to explain how to share spatial data effectively on the web, we need to build on the mechanisms and strengths of the web, which means allowing people to link directly to entities and data points of interest, and use HTTP to deliver information about those things - which leads us to use the Linked Data approach.

Or something like that - to justify the choice of approach and so avoid potential criticism that it was chosen for dogmatic rather than pragmatic reasons.</em>

**Comment by 6a6d74** [comment]
In his [email to the WG](https://lists.w3.org/Archives/Public/public-sdw-wg/2016Jan/0047.html) Clemens says:

<em>"Analysis of the requirements derived from scenarios that describe how spatial data is commonly published and used on the Web (as documented in [UCR]) indicates that, in contrast to the workings of a typical SDI, the Linked Data approach is most appropriate for publishing and using spatial data on the Web. Linked Data provides a foundation to many of the best practices in this document."

Where is that analysis documented and the practical evidence underpinning? Or is it more of an opinion?</em>

**Comment by dret** [comment]
related to #225, #229, #230. http://dret.github.io/webdata/ might be a better foundation, removing the mandate to use one specific metamodel. this would be much more inclusive, while still requiring all the relevant aspects of web architecture.

**Comment by 6a6d74** [comment]
@dret ... in preparation for another release of the BP document we've added a [section about Linked Data](http://w3c.github.io/sdw/bp/#linked-data). 

We're taking a looser view of Linked Data than most and don't see RDF as the only possible encoding. Rather, that the data formats used support web linking.

I think this is quite similar to (or at least consistent with) the [Web Data Principles](http://dret.github.io/webdata/) you cite. 

We're extending DWBP so 'inherit' best practices relating to "Understandable" (3-star) and "Usable" (5-star). I think that [DWBP does this admirably: [§8.3 Data Licenses](http://w3c.github.io/dwbp/bp.html#licenses) and [§8.9 Data Vocabularies](http://w3c.github.io/dwbp/bp.html#dataVocabularies).

What do you think?

**Comment by dret** [comment]
this sounds great. my main problem with "linked data (tm)" is the mandate to use RDF, and that's why http://dret.github.io/webdata/ exists: to encourage people to create good webby data, without mandating a specific metamodel. if that's the path your choosing, that's great, and i am all for that.
just be aware that you might get some backlash from the linked data community when you call something linked data and it's not RDF; that community is rather vocal about the fact that only RDF can be linked data.

**Comment by 6a6d74** [comment]
> just be aware that you might get some backlash from the linked data community when you call something linked data and it's not RDF

@dret: thanks for the heads up! that's a swamp I'd rather avoid :-)

**Comment by dret** [comment]
my solution to the problem is like this:
- i would like to say "linked data" but cannot because of the linked data police.
- i say "webby data" or "web data" (hence http://dret.github.io/webdata/) to highlight the fact that i am talking about data which follows the principles of the web.
- i explain that "linked data" is one specific way to do webby/web data but that the term has a narrower meaning in the community and thus should only be used when this narrower meaning is what you want.
