### ISSUE TITLE
Need consistency in how we cite existing specifications

### ISSUE THREAD

**Issue by 6a6d74** [w3c/sdw#222]
In his [email to the WG](https://lists.w3.org/Archives/Public/public-sdw-wg/2016Jan/0047.html) Clemens says:

<em>Why do some references go to the glossary (eg WFS) and some to the references (eg SPARQL)? Maybe WFS etc should be added to the references, too, and the text should include a link both to the glossary and the references?</em>

**Comment by lvdbrink** [comment]
WFS has been added to the bibliography since this issue was opened. 

To make the document consistent, I suggest we include both a reference to the glossary AND a reference to the bibliography where we talk about standards that also need / have a glossary entry. For example: 

`<a>Resource Description Framework</a> (RDF) [[RDF11-PRIMER]] `

Perhaps not repeating this double reference each time, but only the first time a standard is mentioned in a section. The rest of the mentions can then just be glossary references. 

To make things consistent we also need to go through the text and add glossary references; in some parts of the text this has already been consistently done, in others not.

**Comment by 6a6d74** [comment]
@lvdbrink ... I think this is sensible

**Comment by lvdbrink** [comment]
I will put in a glossary entry the first time a term is mentioned in a paragraph.

**Comment by lvdbrink** [comment]
Done, see PR #808
