### ISSUE TITLE
Update introduction based on review comments

### ISSUE THREAD

**Issue by lvdbrink** [w3c/sdw#48]
The [introduction](http://w3c.github.io/sdw/bp/#intro) is being reviewed by the SDW WG. Review comments are [here](https://lists.w3.org/Archives/Public/public-sdw-wg/2015Nov/0029.html).

**Comment by 6a6d74** [comment]
Other thoughts arising from review of discussions in TPAC; probably you have most of these already ...
- best practices are predicated on using the web as a data sharing platform [WEB ARCH]
- best practices need are designed to be testable by humans and/or machines in order to determine whether you are following them or not
- challenge is combining data that refers to the same place- especially where places and their descriptions are dissimilar … e.g. different levels of granularity
- [statistical data … such as regions identified by NUTS codes used as territorial units for statistics by the European Union]
- not all spatial data is geographic; example: microscopy [see use case 40: TCGA / Microscopy Imaging]
- ¿tools and methods for publishing spatial data?
- spatial data often has a temporal component; things move, boundaries change over time … we include guidance on how to express temporal properties
- environmental data is a special subset of spatial data … we include guidance on how to publish environmental monitoring, such as sensor output, data with sufficient context to unambiguously interpret the values
- different to typical SDI: adoption of the Linked Data approach

**Comment by lvdbrink** [comment]
Intro updated based on mailing list comments and Jeremy's notes.
