### ISSUE TITLE
Devise a way to make best versus emerging practices clearly recognizable in this document.

### ISSUE THREAD

**Issue by lvdbrink** [w3c/sdw#81]
One of our [principles](https://www.w3.org/2015/spatial/wiki/BP_Principles) states: "Best versus emerging practices will be clearly recognizable in this document."

We need to come up with a way to make this clear in the document.

**Comment by 6a6d74** [comment]
Agreed. 

At this weeks call, @philarcher1 notes that DWBP have clustered there practices around benefits- and another group has chosen to use a 'maturity model'. 

Am lacking ideas just now; but thinking about it.

**Comment by ghost** [comment]
I guess the issue is really labelling what we decide is **emerging**,e.g.  approaches that are less mature from the point of view of adoption rather than incompleteness. So for example we might argue that schema.org is emerging, well documented and managed but not yet present on every website ?   

Could we not just add an "Emerging" label to the description with some supporting text in Section 6.1 ?

**Comment by lvdbrink** [comment]
Emerging practices are going to be in a section called Interoperability Issues or something similar and will not be in the body of the BPs.
