### ISSUE TITLE
Range of sosa:isActedOnBy?

### ISSUE THREAD

**Issue by vcharpenay** [w3c/sdw#931]
There is some inconsistency in Fig. 6 & 7, in section [4.3.2 Actuations](https://www.w3.org/TR/vocab-ssn/#h-actuations). The range of property `sosa:isActedOnBy` is defined as `sosa:Actuation` but the figures point to `sosa:Actuator`.

Which statement is the right one?

**Comment by rgcmme** [comment]
Yes, there is an inconsistency. I think that the correct range is sosa:Actuator, since the idea was to keep the parallelism with the observation pattern (observes/isObservedBy).

However, let's ask @arminhaller @dr-shorthair and @kjano

**Comment by maximelefrancois86** [comment]
This "naming inconsistency" is known and has been discussed extensively, but unfortunately we did not reach an agreement. See also figures in https://www.w3.org/2015/spatial/wiki/Link_between_Sensor_and_ObservableProperty

**Comment by maximelefrancois86** [comment]
Hum ok, I see the inconsistency between the figures and the ontology, sorry for not spotting it earlier:

@rgcmme , could you please update Figure 5, 6, 12, so that they reflect the actual axioms in the ontology:

In SOSA: 

- There exists no link between an Actuator and the ActuatableProperty in SOSA, 
- The link from sosa:ActuatableProperty to Actuation is called sosa:isActedOnBy
- The link from sosa:Actuation is called sosa:actsOnProperty

In SSN:

- one can use ssn:forProperty to link from sosa:Actuator to sosa:ActuatableProperty

**Comment by maximelefrancois86** [comment]
Ping @arminhaller

**Comment by rgcmme** [comment]
Figures updated and included in pull request #949.
