### ISSUE TITLE
Use of non-existent sosa:hasProperty in Example B.10 DHT22 Deployment

### ISSUE THREAD

**Issue by GeorgFerdinandSchneider** [w3c/sdw#985]
Dear SOSA-team,

I like to express my gratitude for the excellent work done manifested in the SOSA ontology. 

However, I might have spotted a wrong namespace in the Example B.10 which might be updated in one of the future versions of the document:

```turtle
<Room245> a sosa:FeatureOfInterest ;
  rdfs:label "Room #245"@en ;
  sosa:hasProperty <Room245#temperature> , <Room245#humidity> ;
  sosa:hasSample <Room245/south> .
```

this should be

```turtle
<Room245> a sosa:FeatureOfInterest ;
  rdfs:label "Room #245"@en ;
  ssn:hasProperty <Room245#temperature> , <Room245#humidity> ;
  sosa:hasSample <Room245/south> .
```

as far as I can tell.

best

Georg

**Comment by tidoust** [comment]
Closing this issue:
- The typo was fixed in the Editor's Draft, see [B.10 DHT22 Deployment](https://w3c.github.io/sdw/ssn/#dht22-deployment)
- An entry was added to the Errata document for the published Recommendation, see [Syntax errors in DHT Deployment example](https://www.w3.org/2017/10/vocab-ssn-errata.html#entry-2)
