### ISSUE TITLE
Time ontology uses XML Schema Datatypes that are not allowed in OWL 2

### ISSUE THREAD

**Issue by ElisaKendall** [w3c/sdw#987]
Some of the datatypes specified in the ontology, such as those related to Gregorian calendars (xsd:gDay, xsd:gMonth, and xsd:gYear) as well as xsd:date are not sanctioned for use in OWL 2.  See https://www.w3.org/TR/2012/REC-owl2-quick-reference-20121211/#Built-in_Datatypes_and_Facets for the list of allowable datatypes.

Several of us would like to reuse the W3C Time Ontology in OMG (Object Management Group) standard ontologies, but cannot for this reason.

**Comment by dr-shorthair** [comment]
While the datatypes mentioned are not built-in to OWL2, to our understanding they are not specifically prohibited. 

The original OWL-Time ontology published in 2006  introduced the use of these types. 
So, given the fact that there was extensive use of OWL-Time over the intervening years, in the revision we sought to retain full backward compatibility with all classes and properties that were introduced in the 2006 version. Hence we did not remove any element, though we did mark a few 'deprecated'. 

It is noted in the specification that additional processing will be required if these types are used since they are not built-in to OWL-2.

**Comment by ElisaKendall** [comment]
In https://www.w3.org/TR/2012/REC-owl2-syntax-20121211/, section 4 discusses the set of XML Schema Datatypes that are allowable in OWL.  In particular, that section says:

The rest of this section defines a particular datatype map called the OWL 2 datatype map, which lists the datatypes that can be used in OWL 2 ontologies.

You are correct in that this is a bit subtle, and doesn't say specifically that the others cannot be used, but neither the Functional Syntax nor the mapping to RDF semantics says that they are _**available for use**_ without additional very clear semantics being specified and without requiring additional processing support in tools that choose to implement them.  See https://www.w3.org/TR/2012/REC-owl2-rdf-based-semantics-20121211/#Interpretations under Definition 4.1 for a bit more detail.  

Most OWL 2 compliant tools do not allow extensions to the set of core datatypes at all.  If you choose to use them, the tool behavior is not predictable.  The OWL 2 working group had all kinds of discussions about this - you might look at the historical mailing lists for some of the details, and at minutes from working group notes, since I am not sure where the discussion is captured.  I just remember that there were many heated discussions around datatypes and that the ones we excluded were underspecified.  It's just safer not to use them if you want to foster broad adoption by OWL 2 users.

**Comment by dr-shorthair** [comment]
>  If you choose to use them, the tool behavior is not predictable. 

Indeed. See also the notes regarding OWL processing of the new datatypes here https://www.w3.org/TR/owl-time/#Datatypes 

As mentioned above, we had competing demands. It was felt, given the lengthy period in which the 2006 draft had been on the books and in use, that backward compatibility was very important. So we left the global range constraints on day, month and year in place. We also introduced generalized versions for non-gregorian calendars. 

The Recommendation went through the full W3C process and was available for review as a draft, proposed rec, and candidate rec prior to adoption and we did not receive any comments on this issue. 

The OWL-Time ontology is pretty messy in that it provides multiple options for encoding temporal position - see https://www.w3.org/TR/owl-time/#time-position. IMO the encoding issue would have been best left to a separate layer, with OWL-Time only addressing the conceptual model, but that probably would have surprised practitioners. So we just tried to rationalize what was there, and  accommodate the additional requirements to support non-gregorian calendars and longer time periods and deeper time positions - the latter requiring temporal coordinates rather than date-time style encoding. 

When adopting an RDF vocabulary you will often choose to ignore or suppress some elements. There are RDF technologies to support this, such as SHACL. Perhaps that can help your application? I know OMG likes to have exhaustive automation, but in this case it may have to be partial.

**Comment by dr-shorthair** [comment]
Closed by resolution in SDWIG f2f - Lyon TPAC - 2018-10-23

RESOLUTION: Re #987, we will not make any change to the Time Ontology on the basis that the aim of the Time ontology was to ensure backward compatibility with existing implementations.

https://www.w3.org/2018/10/23-sdw-minutes.html#x08
